quarkus.oidc.auth-server-url=${keycloak.host}/realms/software-credentials
quarkus.oidc.client-id=software-credentials-wallet
quarkus.oidc.credentials.secret=uArydomqOymeF0tBrtipkPYujNNUuDlt
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.pkce-required=true
quarkus.oidc.authentication.cookie-path=/software-credentials-wallet
quarkus.oidc.authentication.scopes=profile
quarkus.oidc.token.age=1H
quarkus.oidc.authentication.force-redirect-https-scheme=${force.redirect.https.scheme:false}

# To workaround a mismatch between NGrock and localhost domains and simplify a demo
quarkus.oidc.token.issuer=any
quarkus.oidc.tls.verification=NONE

quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.grant.type=preauthorized-code

# To workaround a mismatch between NGrock and localhost domains and simplify a demo
quarkus.oidc-client.tls.verification=NONE

quarkus.oidcvc.query-param-credential-id=id

quarkus.hibernate-orm.log.sql=true

wallet.host=${wallet.domain:http://localhost:8080}
issuer.host=${issuer.domain:http://localhost:8081}
verifier.host=${verifier.domain:http://localhost:8082}
keycloak.host=${keycloak.domain:https://localhost:8443}
