quarkus.oidc.auth-server-url=https://quarkus.sandbox.signicat.com/auth/open
quarkus.oidc.client-id=sandbox-thoughtful-comb-551
quarkus.oidc.credentials.secret=43pKWwsf65C8UetVh2qgiEhMY4G6No1QFU8rgWan6b1Yf6B2
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.force-redirect-https-scheme=true

