quarkus.oidc.auth-server-url=${keycloak.host}/realms/software-credentials
quarkus.oidc.token.age=1H
quarkus.oidc.tenant-paths=/best-software-company/presentation
# To workaround a mismatch between NGrock and localhost domains and simplify a demo
#quarkus.oidc.verifier.tls.tls-configuration-name=keycloak
quarkus.oidc.token.issuer=any
quarkus.oidc.tls.verification=NONE

quarkus.tls.keycloak.trust-store.pem.certs=keycloak-certificate.pem
quarkus.tls.keycloak.hostname-verification-algorithm=NONE

wallet.host=${wallet.domain:http://localhost:8080}
issuer.host=${issuer.domain:http://localhost:8081}
verifier.host=${verifier.domain:http://localhost:8082}
keycloak.host=${keycloak.domain:https://localhost:8443}
