#https://github.com/vert-x3/vertx-mail-client/pull/94#issuecomment-399099904
quarkus.mailer.auth-methods=XOAUTH2
quarkus.mailer.username=sberyozkin@gmail.com
quarkus.mailer.password=123456789
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED

quarkus.mailer.mock=false

quarkus.oidc.provider=google
quarkus.oidc.client-id=${GOOGLE_CLIENT_ID}
quarkus.oidc.credentials.secret=${GOOGLE_CLIENT_SECRET}
quarkus.oidc.authentication.extra-params.scope=http://mail.google.com
